---
fixtures:
  repositories:
    stdlib:
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib"
      ref: "4.12.0"
    docker:
      repo: "https://github.com/garethr/garethr-docker"
      ref: " v5.3.0"
    apt:
      repo: "https://github.com/puppetlabs/puppetlabs-apt"
      ref: "2.2.2"
    mysql:
      repo: "https://github.com/puppetlabs/puppetlabs-mysql"
      ref: "3.8.0"
    vision_docker:
      repo: "https://github.com/vision-it/vision-docker"
      ref: "origin/production"
    vision_mysql:
      repo: "https://github.com/vision-it/vision-mysql"
      ref: "origin/production"
    vision_kerberos:
      repo: "https://github.com/vision-it/vision-kerberos"
      ref: "origin/production"
  symlinks:
    vision_bareos: '#{source_dir}'
