---
fixtures:
  repositories:
    stdlib:
      ref: "4.24.0"
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib"
    apt:
      ref: "5.0.1"
      repo: "https://github.com/puppetlabs/puppetlabs-apt"
    mysql:
      ref: "5.4.0"
      repo: "https://github.com/puppetlabs/puppetlabs-mysql"
    vision_mysql:
      repo: "https://github.com/vision-it/vision-mysql"
      ref: "origin/production"
  symlinks:
    vision_bareos: '#{source_dir}'
