---
fixtures:
  repositories:
    stdlib:
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib"
      ref: "4.24.0"
    docker:
      ref: "1.0.4"
      repo: "https://github.com/puppetlabs/puppetlabs-docker"
    apt:
      repo: "https://github.com/puppetlabs/puppetlabs-apt"
      ref: "4.2.0"
    mysql:
      repo: "https://github.com/puppetlabs/puppetlabs-mysql"
      ref: "3.11.0"
    vision_docker:
      repo: "https://github.com/vision-it/vision-docker"
      ref: "origin/production"
    vision_mysql:
      repo: "https://github.com/vision-it/vision-mysql"
      ref: "origin/production"
    vision_kerberos:
      repo: "https://github.com/vision-it/vision-kerberos"
      ref: "origin/production"
  symlinks:
    vision_bareos: '#{source_dir}'
